apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroom-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chatroom-ui
    spec:
      containers:
        - name: chatroom-ui
          image: gauravchaurasiya/chatroom-ui:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: chatroom-ui
---
apiVersion: v1
kind: Service
metadata:
  name: chatroom-ui
spec:
  type: LoadBalancer
  selector:
    app: chatroom-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatroom-ui
data:
  VITE_API_BASE_URL: "http://chatroom-be:5000"
